--
-- PostgreSQL database dump
--

\restrict vd6qaPFfEPb5nYa7hgyQAJAjfoewZe9FV9Ld2kdVgIvTz5G2h1Js5yulj7Qj3KG

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cv_analysis_analyses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_analysis_analyses (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    cv_id bigint NOT NULL,
    full_name character varying(255) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(50) NOT NULL,
    location character varying(255) NOT NULL,
    linkedin_url character varying(200) NOT NULL,
    github_url character varying(200) NOT NULL,
    portfolio_url character varying(200) NOT NULL,
    professional_summary text NOT NULL,
    total_years_experience numeric(4,1),
    highest_degree character varying(100) NOT NULL,
    overall_score integer NOT NULL,
    experience_score integer NOT NULL,
    education_score integer NOT NULL,
    skills_score integer NOT NULL,
    formatting_score integer NOT NULL,
    strengths jsonb NOT NULL,
    weaknesses jsonb NOT NULL,
    suggestions jsonb NOT NULL,
    analysis_version character varying(10) NOT NULL
);


ALTER TABLE public.cv_analysis_analyses OWNER TO postgres;

--
-- Name: cv_analysis_analyses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_analysis_analyses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_analysis_analyses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cv_analysis_cv_skills; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_analysis_cv_skills (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    cv_id bigint NOT NULL,
    skill_id bigint NOT NULL,
    proficiency character varying(20) NOT NULL,
    years_experience numeric(4,1),
    confidence integer NOT NULL,
    context text NOT NULL
);


ALTER TABLE public.cv_analysis_cv_skills OWNER TO postgres;

--
-- Name: cv_analysis_cv_skills_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_analysis_cv_skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_analysis_cv_skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cv_analysis_cvs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_analysis_cvs (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    tenant_id uuid NOT NULL,
    user_id uuid NOT NULL,
    file character varying(100) NOT NULL,
    filename character varying(255) NOT NULL,
    file_type character varying(10) NOT NULL,
    file_size integer NOT NULL,
    status character varying(20) NOT NULL,
    raw_text text NOT NULL,
    processed_at timestamp with time zone,
    processing_error text NOT NULL
);


ALTER TABLE public.cv_analysis_cvs OWNER TO postgres;

--
-- Name: cv_analysis_cvs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_analysis_cvs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_analysis_cvs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cv_analysis_job_matches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_analysis_job_matches (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    cv_id bigint NOT NULL,
    job_id bigint NOT NULL,
    overall_score integer NOT NULL,
    skills_match_score integer NOT NULL,
    experience_match_score integer NOT NULL,
    education_match_score integer NOT NULL,
    matched_skills jsonb NOT NULL,
    missing_skills jsonb NOT NULL,
    match_summary text NOT NULL,
    recommendations jsonb NOT NULL,
    is_bookmarked boolean NOT NULL,
    applied_at timestamp with time zone
);


ALTER TABLE public.cv_analysis_job_matches OWNER TO postgres;

--
-- Name: cv_analysis_job_matches_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_analysis_job_matches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_analysis_job_matches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cv_analysis_analyses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cv_analysis_analyses (id, created_at, updated_at, cv_id, full_name, email, phone, location, linkedin_url, github_url, portfolio_url, professional_summary, total_years_experience, highest_degree, overall_score, experience_score, education_score, skills_score, formatting_score, strengths, weaknesses, suggestions, analysis_version) FROM stdin;
\.


--
-- Data for Name: cv_analysis_cv_skills; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cv_analysis_cv_skills (id, created_at, updated_at, cv_id, skill_id, proficiency, years_experience, confidence, context) FROM stdin;
\.


--
-- Data for Name: cv_analysis_cvs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cv_analysis_cvs (id, created_at, updated_at, tenant_id, user_id, file, filename, file_type, file_size, status, raw_text, processed_at, processing_error) FROM stdin;
1	2025-11-09 17:37:56.284387+00	2025-11-09 17:37:56.284401+00	41576bd7-5c68-4015-9a51-2cb5ae1ba8b4	fee86dd3-4052-4afe-9b0c-a6d2ba640d40	cvs/2025/11/09/CV_Youssef_Hamza.pdf	CV Youssef_Hamza.pdf	pdf	122258	uploaded		\N	
2	2025-11-09 17:38:31.122912+00	2025-11-09 17:38:31.123068+00	41576bd7-5c68-4015-9a51-2cb5ae1ba8b4	fee86dd3-4052-4afe-9b0c-a6d2ba640d40	cvs/2025/11/09/CV_Youssef_Hamza_oY2dLzE.pdf	CV Youssef_Hamza.pdf	pdf	122258	uploaded		\N	
\.


--
-- Data for Name: cv_analysis_job_matches; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cv_analysis_job_matches (id, created_at, updated_at, cv_id, job_id, overall_score, skills_match_score, experience_match_score, education_match_score, matched_skills, missing_skills, match_summary, recommendations, is_bookmarked, applied_at) FROM stdin;
\.


--
-- Name: cv_analysis_analyses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cv_analysis_analyses_id_seq', 1, false);


--
-- Name: cv_analysis_cv_skills_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cv_analysis_cv_skills_id_seq', 1, false);


--
-- Name: cv_analysis_cvs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cv_analysis_cvs_id_seq', 33, true);


--
-- Name: cv_analysis_job_matches_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cv_analysis_job_matches_id_seq', 1, false);


--
-- Name: cv_analysis_analyses cv_analysis_analyses_cv_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_analysis_analyses
    ADD CONSTRAINT cv_analysis_analyses_cv_id_key UNIQUE (cv_id);


--
-- Name: cv_analysis_analyses cv_analysis_analyses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_analysis_analyses
    ADD CONSTRAINT cv_analysis_analyses_pkey PRIMARY KEY (id);


--
-- Name: cv_analysis_cv_skills cv_analysis_cv_skills_cv_id_skill_id_0857dc99_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_analysis_cv_skills
    ADD CONSTRAINT cv_analysis_cv_skills_cv_id_skill_id_0857dc99_uniq UNIQUE (cv_id, skill_id);


--
-- Name: cv_analysis_cv_skills cv_analysis_cv_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_analysis_cv_skills
    ADD CONSTRAINT cv_analysis_cv_skills_pkey PRIMARY KEY (id);


--
-- Name: cv_analysis_cvs cv_analysis_cvs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_analysis_cvs
    ADD CONSTRAINT cv_analysis_cvs_pkey PRIMARY KEY (id);


--
-- Name: cv_analysis_job_matches cv_analysis_job_matches_cv_id_job_id_3102b2db_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_analysis_job_matches
    ADD CONSTRAINT cv_analysis_job_matches_cv_id_job_id_3102b2db_uniq UNIQUE (cv_id, job_id);


--
-- Name: cv_analysis_job_matches cv_analysis_job_matches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_analysis_job_matches
    ADD CONSTRAINT cv_analysis_job_matches_pkey PRIMARY KEY (id);


--
-- Name: cv_analysis_cv_id_3260d8_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cv_analysis_cv_id_3260d8_idx ON public.cv_analysis_job_matches USING btree (cv_id, overall_score DESC);


--
-- Name: cv_analysis_cv_skills_cv_id_b4cae295; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cv_analysis_cv_skills_cv_id_b4cae295 ON public.cv_analysis_cv_skills USING btree (cv_id);


--
-- Name: cv_analysis_cv_skills_skill_id_28708b2d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cv_analysis_cv_skills_skill_id_28708b2d ON public.cv_analysis_cv_skills USING btree (skill_id);


--
-- Name: cv_analysis_cvs_tenant_id_f07480bb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cv_analysis_cvs_tenant_id_f07480bb ON public.cv_analysis_cvs USING btree (tenant_id);


--
-- Name: cv_analysis_cvs_user_id_1fcc4309; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cv_analysis_cvs_user_id_1fcc4309 ON public.cv_analysis_cvs USING btree (user_id);


--
-- Name: cv_analysis_job_id_4e2d3a_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cv_analysis_job_id_4e2d3a_idx ON public.cv_analysis_job_matches USING btree (job_id, overall_score DESC);


--
-- Name: cv_analysis_job_matches_cv_id_5c9ff6e9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cv_analysis_job_matches_cv_id_5c9ff6e9 ON public.cv_analysis_job_matches USING btree (cv_id);


--
-- Name: cv_analysis_job_matches_job_id_da2ae0ce; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cv_analysis_job_matches_job_id_da2ae0ce ON public.cv_analysis_job_matches USING btree (job_id);


--
-- Name: cv_analysis_status_7e468a_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cv_analysis_status_7e468a_idx ON public.cv_analysis_cvs USING btree (status);


--
-- Name: cv_analysis_tenant__a09bd2_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cv_analysis_tenant__a09bd2_idx ON public.cv_analysis_cvs USING btree (tenant_id, created_at DESC);


--
-- Name: cv_analysis_user_id_21a038_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cv_analysis_user_id_21a038_idx ON public.cv_analysis_cvs USING btree (user_id, created_at DESC);


--
-- Name: cv_analysis_analyses cv_analysis_analyses_cv_id_c4c8f69b_fk_cv_analysis_cvs_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_analysis_analyses
    ADD CONSTRAINT cv_analysis_analyses_cv_id_c4c8f69b_fk_cv_analysis_cvs_id FOREIGN KEY (cv_id) REFERENCES public.cv_analysis_cvs(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cv_analysis_cv_skills cv_analysis_cv_skill_skill_id_28708b2d_fk_cv_analys; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_analysis_cv_skills
    ADD CONSTRAINT cv_analysis_cv_skill_skill_id_28708b2d_fk_cv_analys FOREIGN KEY (skill_id) REFERENCES public.cv_analysis_skills(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cv_analysis_cv_skills cv_analysis_cv_skills_cv_id_b4cae295_fk_cv_analysis_cvs_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_analysis_cv_skills
    ADD CONSTRAINT cv_analysis_cv_skills_cv_id_b4cae295_fk_cv_analysis_cvs_id FOREIGN KEY (cv_id) REFERENCES public.cv_analysis_cvs(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cv_analysis_cvs cv_analysis_cvs_tenant_id_f07480bb_fk_tenants_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_analysis_cvs
    ADD CONSTRAINT cv_analysis_cvs_tenant_id_f07480bb_fk_tenants_id FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cv_analysis_cvs cv_analysis_cvs_user_id_1fcc4309_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_analysis_cvs
    ADD CONSTRAINT cv_analysis_cvs_user_id_1fcc4309_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cv_analysis_job_matches cv_analysis_job_matc_job_id_da2ae0ce_fk_cv_analys; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_analysis_job_matches
    ADD CONSTRAINT cv_analysis_job_matc_job_id_da2ae0ce_fk_cv_analys FOREIGN KEY (job_id) REFERENCES public.cv_analysis_job_postings(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cv_analysis_job_matches cv_analysis_job_matches_cv_id_5c9ff6e9_fk_cv_analysis_cvs_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_analysis_job_matches
    ADD CONSTRAINT cv_analysis_job_matches_cv_id_5c9ff6e9_fk_cv_analysis_cvs_id FOREIGN KEY (cv_id) REFERENCES public.cv_analysis_cvs(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict vd6qaPFfEPb5nYa7hgyQAJAjfoewZe9FV9Ld2kdVgIvTz5G2h1Js5yulj7Qj3KG

