# Generated by Django 4.2.26 on 2025-11-09 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvancedCVAnalysis",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ats_score", models.IntegerField()),
                ("ats_report", models.TextField()),
                ("job_description", models.TextField(blank=True)),
                ("match_score", models.IntegerField(blank=True, null=True)),
                ("matching_report", models.TextField(blank=True)),
                ("extracted_skills", models.JSONField(blank=True, default=list)),
                ("experience_summary", models.TextField(blank=True)),
                (
                    "total_years",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("education_summary", models.TextField(blank=True)),
                ("formatted_cv_url", models.URLField(blank=True)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "advanced_cv_analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="cvs/%Y/%m/%d/")),
                ("filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=10)),
                ("file_size", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("analyzed", "Analyzed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("raw_text", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CV",
                "verbose_name_plural": "CVs",
                "db_table": "cv_analysis_cvs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("draft", "Draft"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                (
                    "years_experience_required",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "cv_analysis_job_postings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=50)),
                ("synonyms", models.JSONField(blank=True, default=list)),
                ("importance_weight", models.FloatField(default=1.0)),
            ],
            options={
                "db_table": "cv_analysis_skills",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="cv_analysis_categor_800554_idx"
                    ),
                    models.Index(fields=["name"], name="cv_analysis_name_07c4e0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("overall_score", models.IntegerField()),
                ("skills_match_score", models.IntegerField()),
                ("experience_match_score", models.IntegerField()),
                ("education_match_score", models.IntegerField()),
                ("matched_skills", models.JSONField(blank=True, default=list)),
                ("missing_skills", models.JSONField(blank=True, default=list)),
                ("match_summary", models.TextField(blank=True)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("is_bookmarked", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_matches",
                        to="cv_analysis.cv",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_matches",
                        to="cv_analysis.jobposting",
                    ),
                ),
            ],
            options={
                "db_table": "cv_analysis_job_matches",
                "ordering": ["-overall_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("achievements", models.JSONField(blank=True, default=list)),
                ("duration_months", models.IntegerField(blank=True, null=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="cv_analysis.cv",
                    ),
                ),
            ],
            options={
                "db_table": "cv_analysis_experiences",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("institution", models.CharField(max_length=255)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("associate", "Associate Degree"),
                            ("bachelor", "Bachelor's Degree"),
                            ("master", "Master's Degree"),
                            ("phd", "PhD"),
                            ("certificate", "Certificate"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("field_of_study", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("grade", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="cv_analysis.cv",
                    ),
                ),
            ],
            options={
                "db_table": "cv_analysis_education",
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="CVSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proficiency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "years_experience",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("confidence", models.IntegerField(default=0)),
                ("context", models.TextField(blank=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="cv_analysis.cv",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_skills",
                        to="cv_analysis.skill",
                    ),
                ),
            ],
            options={
                "db_table": "cv_analysis_cv_skills",
                "ordering": ["-confidence", "skill__name"],
            },
        ),
        migrations.CreateModel(
            name="CVJobMatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("job_description", models.TextField()),
                ("match_score", models.IntegerField()),
                ("matched_skills", models.JSONField(blank=True, default=list)),
                ("missing_skills", models.JSONField(blank=True, default=list)),
                ("matching_report", models.TextField()),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("is_free_match", models.BooleanField(default=False)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_job_matches",
                        to="cv_analysis.cv",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_job_matches",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_job_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cv_job_matches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CVAnalysisUsageTracker",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "module_type",
                    models.CharField(
                        choices=[
                            ("ats_detailed", "ATS Detailed Reports"),
                            ("cv_matcher", "CV-Job Matches"),
                        ],
                        max_length=50,
                    ),
                ),
                ("free_limit", models.IntegerField(default=3)),
                ("used_count", models.IntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_usage_trackers",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "cv_analysis_usage_trackers",
            },
        ),
        migrations.CreateModel(
            name="CVAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                ("professional_summary", models.TextField(blank=True)),
                (
                    "total_years_experience",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("highest_degree", models.CharField(blank=True, max_length=100)),
                ("overall_score", models.IntegerField(default=0)),
                ("experience_score", models.IntegerField(default=0)),
                ("education_score", models.IntegerField(default=0)),
                ("skills_score", models.IntegerField(default=0)),
                ("formatting_score", models.IntegerField(default=0)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                ("suggestions", models.JSONField(blank=True, default=list)),
                ("analysis_version", models.CharField(default="1.0", max_length=10)),
                (
                    "cv",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="cv_analysis.cv",
                    ),
                ),
            ],
            options={
                "verbose_name": "CV Analysis",
                "verbose_name_plural": "CV Analyses",
                "db_table": "cv_analysis_analyses",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "advanced_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="cv_analysis.advancedcvanalysis",
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ATSAnalysis",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ats_score", models.IntegerField()),
                ("formatting_issues", models.JSONField(blank=True, default=list)),
                ("keyword_issues", models.JSONField(blank=True, default=list)),
                ("has_detailed_report", models.BooleanField(default=False)),
                ("detailed_explanation", models.TextField(blank=True)),
                ("improvement_suggestions", models.JSONField(blank=True, default=list)),
                ("section_scores", models.JSONField(blank=True, default=dict)),
                ("is_free_detailed_report", models.BooleanField(default=False)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ats_analyses",
                        to="cv_analysis.cv",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ats_analyses",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ats_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ats_analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="advancedcvanalysis",
            name="cv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advanced_analyses",
                to="cv_analysis.cv",
            ),
        ),
        migrations.AddField(
            model_name="advancedcvanalysis",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advanced_analyses",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="advancedcvanalysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advanced_analyses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="JobSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requirement_level",
                    models.CharField(
                        choices=[
                            ("required", "Required"),
                            ("preferred", "Preferred"),
                            ("nice_to_have", "Nice to Have"),
                        ],
                        default="required",
                        max_length=20,
                    ),
                ),
                (
                    "years_required",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_skills",
                        to="cv_analysis.jobposting",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_skills",
                        to="cv_analysis.skill",
                    ),
                ),
            ],
            options={
                "db_table": "cv_analysis_job_skills",
                "unique_together": {("job", "skill")},
            },
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["tenant", "status", "-created_at"],
                name="cv_analysis_tenant__b4b364_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(fields=["status"], name="cv_analysis_status_1cf535_idx"),
        ),
        migrations.AddIndex(
            model_name="jobmatch",
            index=models.Index(
                fields=["cv", "-overall_score"], name="cv_analysis_cv_id_3260d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobmatch",
            index=models.Index(
                fields=["job", "-overall_score"], name="cv_analysis_job_id_4e2d3a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobmatch",
            unique_together={("cv", "job")},
        ),
        migrations.AlterUniqueTogether(
            name="cvskill",
            unique_together={("cv", "skill")},
        ),
        migrations.AlterUniqueTogether(
            name="cvanalysisusagetracker",
            unique_together={("tenant", "module_type")},
        ),
        migrations.AddIndex(
            model_name="cv",
            index=models.Index(
                fields=["tenant", "-created_at"], name="cv_analysis_tenant__a09bd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cv",
            index=models.Index(
                fields=["user", "-created_at"], name="cv_analysis_user_id_21a038_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cv",
            index=models.Index(fields=["status"], name="cv_analysis_status_7e468a_idx"),
        ),
    ]
