# Generated by Django 4.2.26 on 2025-11-11 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv_analysis", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="atsanalysis",
            old_name="detailed_explanation",
            new_name="detailed_report",
        ),
        migrations.RenameField(
            model_name="atsanalysis",
            old_name="formatting_issues",
            new_name="keyword_matches",
        ),
        migrations.RenameField(
            model_name="atsanalysis",
            old_name="improvement_suggestions",
            new_name="missing_keywords",
        ),
        migrations.RenameField(
            model_name="atsanalysis",
            old_name="keyword_issues",
            new_name="quick_suggestions",
        ),
        migrations.RemoveField(
            model_name="atsanalysis",
            name="section_scores",
        ),
    ]
