# Generated by Django 4.2.26 on 2025-11-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cv_analysis",
            "0002_rename_detailed_explanation_atsanalysis_detailed_report_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advancedcvanalysis",
            name="ats_report",
        ),
        migrations.RemoveField(
            model_name="advancedcvanalysis",
            name="ats_score",
        ),
        migrations.RemoveField(
            model_name="advancedcvanalysis",
            name="education_summary",
        ),
        migrations.RemoveField(
            model_name="advancedcvanalysis",
            name="experience_summary",
        ),
        migrations.RemoveField(
            model_name="advancedcvanalysis",
            name="extracted_skills",
        ),
        migrations.RemoveField(
            model_name="advancedcvanalysis",
            name="formatted_cv_url",
        ),
        migrations.RemoveField(
            model_name="advancedcvanalysis",
            name="job_description",
        ),
        migrations.RemoveField(
            model_name="advancedcvanalysis",
            name="match_score",
        ),
        migrations.RemoveField(
            model_name="advancedcvanalysis",
            name="matching_report",
        ),
        migrations.RemoveField(
            model_name="advancedcvanalysis",
            name="recommendations",
        ),
        migrations.RemoveField(
            model_name="advancedcvanalysis",
            name="total_years",
        ),
        migrations.AddField(
            model_name="advancedcvanalysis",
            name="career_recommendations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="advancedcvanalysis",
            name="full_analysis",
            field=models.TextField(blank=True, default="Analysis in progress..."),
        ),
        migrations.AddField(
            model_name="advancedcvanalysis",
            name="improvement_suggestions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="advancedcvanalysis",
            name="strengths",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="advancedcvanalysis",
            name="weaknesses",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="advancedcvanalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
    ]
