# Generated by Django 4.2.26 on 2025-11-14 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("behavioral", "Behavioral"),
                            ("case_study", "Case Study"),
                            ("system_design", "System Design"),
                            ("cultural_fit", "Cultural Fit"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("job_role", models.CharField(blank=True, max_length=255)),
                ("experience_level", models.CharField(blank=True, max_length=50)),
                ("duration_minutes", models.IntegerField(default=30)),
                ("question_count", models.IntegerField(default=10)),
                ("is_public", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_templates",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "interviews_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("coding", "Coding"),
                            ("open_ended", "Open Ended"),
                            ("behavioral", "Behavioral"),
                            ("system_design", "System Design"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField()),
                ("context", models.TextField(blank=True)),
                ("options", models.JSONField(blank=True, default=list)),
                ("correct_answer", models.TextField(blank=True)),
                ("starter_code", models.TextField(blank=True)),
                ("test_cases", models.JSONField(blank=True, default=list)),
                ("ideal_answer", models.TextField(blank=True)),
                ("evaluation_criteria", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("time_limit_seconds", models.IntegerField(default=300)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="interviews.interviewtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "interviews_questions",
                "ordering": ["difficulty", "question_type"],
            },
        ),
        migrations.CreateModel(
            name="PracticeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("area_name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("questions_attempted", models.IntegerField(default=0)),
                ("questions_correct", models.IntegerField(default=0)),
                ("total_practice_time_minutes", models.IntegerField(default=0)),
                ("current_score", models.IntegerField(default=0)),
                ("best_score", models.IntegerField(default=0)),
                ("last_practiced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_areas",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_areas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "interviews_practice_areas",
                "ordering": ["-last_practiced_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("job_role", models.CharField(blank=True, max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("practice", "Practice Mode"),
                            ("simulation", "Real Simulation"),
                        ],
                        default="practice",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("overall_score", models.IntegerField(default=0)),
                ("technical_score", models.IntegerField(default=0)),
                ("communication_score", models.IntegerField(default=0)),
                ("confidence_score", models.IntegerField(default=0)),
                ("problem_solving_score", models.IntegerField(default=0)),
                ("overall_feedback", models.TextField(blank=True)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("areas_for_improvement", models.JSONField(blank=True, default=list)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("interviewer_avatar_url", models.URLField(blank=True)),
                ("recording_url", models.URLField(blank=True)),
                ("transcript", models.TextField(blank=True)),
                ("response_times", models.JSONField(blank=True, default=list)),
                ("filler_words_count", models.IntegerField(default=0)),
                ("speaking_pace", models.CharField(blank=True, max_length=20)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="interviews.interviewtemplate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "interviews_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("technical_analysis", models.TextField(blank=True)),
                ("communication_analysis", models.TextField(blank=True)),
                ("problem_solving_analysis", models.TextField(blank=True)),
                ("strong_areas", models.JSONField(blank=True, default=list)),
                ("weak_areas", models.JSONField(blank=True, default=list)),
                ("study_topics", models.JSONField(blank=True, default=list)),
                ("resource_links", models.JSONField(blank=True, default=list)),
                ("percentile_rank", models.IntegerField(blank=True, null=True)),
                ("recommended_difficulty", models.CharField(blank=True, max_length=20)),
                ("ready_for_real_interview", models.BooleanField(default=False)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailed_feedback",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview Feedback",
                "verbose_name_plural": "Interview Feedback",
                "db_table": "interviews_feedback",
            },
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("interviewer", "AI Interviewer"),
                            ("candidate", "User/Candidate"),
                            ("system", "System Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("audio_url", models.URLField(blank=True)),
                ("duration_seconds", models.FloatField(default=0)),
                ("sentiment", models.CharField(blank=True, max_length=20)),
                ("confidence_score", models.IntegerField(default=0)),
                ("keywords_detected", models.JSONField(blank=True, default=list)),
                ("timestamp_seconds", models.FloatField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_messages",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "db_table": "interviews_conversation_messages",
                "ordering": ["session", "timestamp_seconds"],
            },
        ),
        migrations.CreateModel(
            name="SessionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.IntegerField(default=0)),
                ("user_answer", models.TextField(blank=True)),
                ("code_submission", models.TextField(blank=True)),
                ("execution_result", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("time_taken_seconds", models.IntegerField(default=0)),
                ("is_correct", models.BooleanField(default=False)),
                ("score", models.IntegerField(default=0)),
                ("ai_evaluation", models.TextField(blank=True)),
                ("sentiment", models.CharField(blank=True, max_length=20)),
                ("confidence_level", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_questions",
                        to="interviews.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_questions",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "db_table": "interviews_session_questions",
                "ordering": ["session", "order"],
                "unique_together": {("session", "question")},
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["template"], name="interviews__templat_050b2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["question_type", "difficulty"],
                name="interviews__questio_05ca4e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="practicearea",
            unique_together={("user", "tenant", "area_name")},
        ),
        migrations.AddIndex(
            model_name="interviewtemplate",
            index=models.Index(
                fields=["tenant", "is_active"], name="interviews__tenant__e6f67b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewtemplate",
            index=models.Index(
                fields=["interview_type", "difficulty"],
                name="interviews__intervi_fb8234_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interviewsession",
            index=models.Index(
                fields=["tenant", "user", "-created_at"],
                name="interviews__tenant__d55ad7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interviewsession",
            index=models.Index(fields=["status"], name="interviews__status_9ef962_idx"),
        ),
        migrations.AddIndex(
            model_name="conversationmessage",
            index=models.Index(
                fields=["session", "timestamp_seconds"],
                name="interviews__session_750fc6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationmessage",
            index=models.Index(fields=["role"], name="interviews__role_399b0c_idx"),
        ),
    ]
