# Generated by Django 4.2.26 on 2025-11-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_create_conversation_messages"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversationmessage",
            new_name="interviews__session_750fc6_idx",
            old_name="interviews_session_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationmessage",
            new_name="interviews__role_399b0c_idx",
            old_name="interviews_role_idx",
        ),
    ]
